### ISSUE TITLE
Replace RequestFilter with HTTPMiddleware

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versionfeed#44]
As RequestFilter is now deprecated we should replace it with a middleware instead

**Comment by NightJar** [comment]
There are no instances or references of "RequestFilter" in the code. The filters present are for filtering the versions, not requests - an also appear to be a slight misnomer as the defaults are essentially just a cache.

**Comment by robbieaverill** [comment]
True! Nice 😆
