### ISSUE TITLE
Fix unit tests and ensure Travis is passing

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versionfeed#47]

**Comment by NightJar** [comment]
I've traced the misfunctionality of `allchanges` back through to the logic the module uses with `SilverStripe/Versioned`. The logic and construction of Versioned is very complex, and it's not obvious how to proceed with getting the correct data back out, even with using manual queries such as what is being upgraded from.

The issue I have at the moment is that the query appears to expect `SiteTree` objects, however recieves `Versioned_Version` objects instead. Even if we adapt the inflation method to return `SiteTree`, multi-model data such as `AbsoluteLink()` would see that we reference information on the parent object at the _current_ version, creating a conundrum of versional information mismatches (meaning the 'version' we get out may not be an accurate portrayal of the page at that time in full).

https://github.com/silverstripe/silverstripe-versionfeed/blob/master/src/VersionFeedController.php#L108

Referencing this query specifically with the issues above (and the reason the tests are failing), this work ultimately ties in with cleaning this up.

**Comment by robbieaverill** [comment]
So far as I can tell the changes at #49 fix this issue

**Comment by NightJar** [comment]
I'm afraid I'm unconvinced. #49 makes the tests pass perhaps, but they're not very validatory as it is, unfortunately.

**Comment by NightJar** [comment]
After we looked into this I now remain convinced. Nice :) Team work makes the dream work.
